Account management new
mozilla-rally/rally-web-platform pull request #205
Opened 2022-02-08 05:03 UTC by Carla-Moz

This is a hefty PR and I apologize in advance. I promise future PRs won't be so large.

Major changes included for platform:

1. Centered container for all pages
2. Navbar and footer with routes to pages and external links 
3. Sign-out functionality in drop-down of navbar 
4. New account management styles which will probably change so let's keep as placeholder for now
5. Added Sass to the platform; there are still some lingering in line styles that need cleaning up as the sass file evolve. Might also be some repeating styles which I'll clean in next PR.
6. Not responsive yet; that's for the next PR.

2022-02-08 17:46 UTC, rhelmer requested changes
lgtm overall, I didn't focus on the style changes too much (except verifying that it looks and works ok visually), just a few minor things I noticed.

2022-02-08 21:20 UTC, Carla-Moz commented on firebase.config.json
> +{
Yeah, this was accidentally removed from the static folder. Good catch. Thanks

2022-02-08 21:25 UTC, Carla-Moz commented on src/app.html
> +/>
Oh prettier must have formatted it that way.

2022-02-08 21:35 UTC, Carla-Moz commented on src/lib/components/auth-cards/LaunchCard.svelte
> +          }, 1000);
Hm, not sure, maybe I was playing around with seeing the spinner a little but longer before signing in. So unnecessary haha.

2022-02-08 21:36 UTC, Carla-Moz commented on src/lib/views/account-settings/UpdatePassword.svelte
> +  console.log("store", store);
Ack forgot to clean those up. Thanks

2022-02-08 21:37 UTC, Carla-Moz commented on src/routes/_Sidebar.svelte
> +      <!-- <li in:fly={{ duration: 800, delay: 400, x: -15 }}>
Yes, meant to remove.

2022-02-08 21:37 UTC, Carla-Moz commented on src/routes/account-settings/index.svelte
> +    console.log("event", event.detail.text);
Yup

2022-02-08 21:41 UTC, Carla-Moz commented on src/stories/components/account/StorySettingsReadOnly.svelte
> +        handleSelect(listArr[0]);
Yes, true. Was originally an array of objects. Not sure why I changed it. Thanks.

2022-02-09 22:03 UTC, stansky approved these changes

2022-02-10 16:10 UTC, merged